### NUMPY

In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.6 MB 1.6 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/12.6 MB 1.6 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.6 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.6 MB 1.9 MB/s eta 0:00:06
   ---------- ----------------------------- 3.1/12.6 MB 2.0 MB/s eta 0:00:05
   ---------- ----------------------------- 3.1/12.6 MB 2.0 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.6 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.6 MB 1.8 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.6 MB 1.7 MB/s eta 0:00:05
   ----------

In [2]:
import numpy as np

In [15]:
# 1-D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(5,)

In [8]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [14]:
# 2-D array
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [28]:
a = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [29]:
a.shape

(2, 2, 3)

In [30]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [34]:
print(a.reshape(2,3,2))
print(a.reshape(2,3,2).shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 12]
  [13 14]
  [15 16]]]
(2, 3, 2)


In [37]:
# in-built functions in numpy
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [48]:
## Basic attributes of Numpy array:
print(a.ndim, "Dimensions")
print(a.shape, "Shape")
print(a.size, "Size of the matrix or array or number of elements")
print(a.dtype, "Data type")
print(a.itemsize, "Size of individual array element in byte")
print(a.nbytes, "Total size of array elements in bytes")

3 Dimensions
(2, 2, 3) Shape
12 Size of the matrix or array or number of elements
int64 Data type
8 Size of individual array element in byte
96 Total size of array elements in bytes


In [51]:
## Numpy Vectorized operations: 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

print(arr1,arr2)

# Element-wise Addition
print(arr1 + arr2)

# Element-wise Subtraction
print(arr1 - arr2)

# Element-wise Multiplication
print(arr1 * arr2)

# Element-wise Division
print(arr1 / arr2)

# the returned output is also an array 

[1 2 3 4 5] [5 6 7 8 9]
[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [53]:
## Universal Function - Some functions that apply across the array. 
arr = np.array([1,2,3,4,5])

#Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [63]:
# Array Slicing and Indexing: 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])
print(arr)

print(arr[0][0])
print(arr[0,0])
print(arr[2,2])
print(arr[0:3])

print(arr[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
1
1
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[7 8 9]


In [65]:
## Modify the array elements
print(arr)

arr[0,0] = 100

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [66]:
arr[1:]=99
print(arr)

[[100   2   3   4   5]
 [ 99  99  99  99  99]
 [ 99  99  99  99  99]]


In [1]:
# Statistical Concepts - Normalization
# To have a mean of 0 and and standard deviation of 1

# Normalization is done to achieve the above config to make calculations easier. 

In [3]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
print(np.mean(a), "- Mean")

#Median
print(np.median(a),"- Median")

# Standard Deviation
print(np.std(a),"- Std. Deviation")

# Variance
print(np.var(a),"- Variance")


5.5 - Mean
5.5 - Median
2.8722813232690143 - Std. Deviation
8.25 - Variance


In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[10,11],[12,13]])

print(a+b)

[[11 13]
 [15 17]]


In [17]:
#Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[data>5])
print(data[data<8])
print(data[(data >= 5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[1 2 3 4 5 6 7]
[5 6 7 8]
