In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.zeros(3)

In [11]:
arr3

array([0., 0., 0.])

In [12]:
arr4 = np.zeros((2,3))

In [13]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [15]:
arr5 = np.ones(4)

In [16]:
arr5

array([1., 1., 1., 1.])

In [19]:
arr6 = np.ones((4,5))

In [20]:
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
arr7 = np.identity(5)

In [22]:
arr7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr8 = np.arange(10)

In [24]:
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr9 = np.linspace(10,20,10)

In [26]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [27]:
arr10 = arr9.copy()

In [28]:
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [29]:
arr1.shape

(4,)

In [30]:
arr2.shape

(2, 3)

In [31]:
arr3

array([0., 0., 0.])

In [32]:
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
arr5

array([1., 1., 1., 1.])

In [34]:
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
arr6.ndim

2

In [36]:
arr6.shape

(4, 5)

In [42]:
arr11 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [10,20,30],
        [11,22,33]
    ]
])

In [43]:
arr11

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [11, 22, 33]]])

In [44]:
arr12 = np.array([[[1,2,3],[4,5,6]],[[10,20,30],[11,22,33]]])

In [45]:
arr12

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [11, 22, 33]]])

In [46]:
arr12.size

12

In [47]:
arr12.shape

(2, 2, 3)

In [51]:
arr12.itemsize

# this attribute basically gives the number of bytes it required to store a single element. 
# here it was an integer so they only take 4 bytes of memory.


4

In [49]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [52]:
arr9.itemsize

# floats take 8 bytes of memory.

8

In [54]:
arr12.dtype

dtype('int32')

In [55]:
arr9.dtype

dtype('float64')

In [56]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [57]:
arr11

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [11, 22, 33]]])

In [58]:
arr11.astype("float")

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[10., 20., 30.],
        [11., 22., 33.]]])

In [59]:
lista=range(100)
arr = np.arange(100)

In [60]:
import sys

In [62]:
print(sys.getsizeof(87)*len(lista))

# here 87 is just a random number whose size is determined and then multiplied by the length of the list to get total 
# size in bytes which is used to store the list. 

2800


In [63]:
print(arr.itemsize*arr.size)

400


In [64]:
import time

In [79]:
x = range(10000000)
y = range(10000000,20000000)

In [80]:
start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time() - start_time)

1.9209702014923096


In [81]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start_time = time.time()
c = a+b

print(time.time()-start_time)

0.20562100410461426


In [83]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [84]:
arr1 

array([1, 2, 3, 4])

In [85]:
arr1[3]

4

In [86]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [113]:
arr12[0:4,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [111]:
arr12[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [116]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [118]:
arr12[:,2:4][1:3]

array([[ 6,  7],
       [10, 11]])

In [119]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [121]:
arr12[:,1:3][2:4]

array([[ 9, 10],
       [13, 14]])

In [122]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [123]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [124]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [125]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [126]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [127]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [128]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [129]:
arr2 - arr1

array([5, 5, 5, 5, 5])

In [130]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [131]:
arr1*2

array([ 2,  4,  6,  8, 10])

In [132]:
np.empty(2)

array([1.52254937e-311, 0.00000000e+000])

In [133]:
a = np.array([[1,2],[3,4]])

In [139]:
b = np.array([[5,6]])

In [140]:
a+b

array([[ 6,  8],
       [ 8, 10]])

In [141]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [143]:
b.ndim

2

In [144]:
arr1

array([1, 2, 3, 4, 5])

In [145]:
arr1 > 3

array([False, False, False,  True,  True])

In [146]:
import time

In [173]:
a = range(100000000)
b=[]

start_time = time.time()

for i in a: 
    b.append(i+5)
b
print(time.time() - start_time)

25.652546882629395


In [167]:
import numpy

In [174]:
x = np.arange(100000000)

start_time = time.time()

y = x+5

print(time.time() - start_time)

0.250046968460083


In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [5]:
a.itemsize

4

In [6]:
a.dtype

dtype('int32')

In [11]:
b = np.array([0.1,0.2,0.3])

In [12]:
b.itemsize

8

In [13]:
ndarray.data

NameError: name 'ndarray' is not defined

In [14]:
b.data

In [15]:
np.array(1,2)

TypeError: Cannot interpret '2' as a data type

In [17]:
c = np.array(1)

In [18]:
c

array(1)

In [19]:
d = np.array([1,2])

In [20]:
d

array([1, 2])

In [21]:
type(c)

numpy.ndarray

In [22]:
c.dtype

dtype('int32')

In [23]:
type(d)

numpy.ndarray

In [24]:
d.dtype

dtype('int32')

In [25]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [27]:
np.zeros(2)

array([0., 0.])

In [28]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 0)

In [31]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones([2,3], dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [35]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [38]:
np.linspace(10,30,5)

array([10., 15., 20., 25., 30.])

In [39]:
pip list

Package                           Version
--------------------------------- ------------------
aiobotocore                       2.12.3
aiohttp                           3.9.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.5.1
anaconda-navigator                2.6.0
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.0
astropy-iers-data                 0.2024.6.3.0.31.14
astto

In [40]:
a = np.array([1,2,3,4])

In [41]:
a

array([1, 2, 3, 4])

In [42]:
a[0]

1

In [43]:
a[:2]

array([1, 2])

In [44]:
a[1:]

array([2, 3, 4])

In [45]:
a

array([1, 2, 3, 4])

In [46]:
b

array([0.1, 0.2, 0.3])

In [47]:
c

array(1)

In [48]:
a=np.array([1,2,3,4,5])

In [50]:
b=a.copy()

In [51]:
b

array([1, 2, 3, 4, 5])

In [52]:
b[1]=999

In [53]:
b

array([  1, 999,   3,   4,   5])

In [54]:
a

array([1, 2, 3, 4, 5])

In [66]:
c = a[1:]

In [56]:
a[1:][0] = 8888

In [57]:
a

array([   1, 8888,    3,    4,    5])

In [58]:
b

array([  1, 999,   3,   4,   5])

In [59]:
# copy method gives you a duplicate copy of an array upon which any changes done, doesnt make any difference on the original one.

In [60]:
# if we just tweak or look at the original array in a diff way like, slicing, indexing, its all done on a view array 
# any slicing or step-size look on these views doesnt change the actual internal data buffer. It is only when you change 
# any element in a view it reflects on the original array. 

In [62]:
a.base is None

True

In [63]:
b.base is None

True

In [64]:
a.base

In [65]:
b.base

In [67]:
c.base

array([   1, 8888,    3,    4,    5])

In [68]:
# one way to differentiate copy from a view is by using .base attribute. If we are using .base on an array if it gives 
# the original array as an output, then its a view and if there's no output, then its a copy. 

In [69]:
c.base is None

False

In [70]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a[1,3]

8

In [72]:
# ndim, shape, size, dtype are major attributes of Numpy arrays. 

In [73]:
# np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace() are some of the major methods that creates a basic array. 

In [76]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x = np.array([2,3,1,5,1,6,8,10,5,1])

In [82]:
x

array([ 2,  3,  1,  5,  1,  6,  8, 10,  5,  1])

In [83]:
x.sort()

In [84]:
x

array([ 1,  1,  1,  2,  3,  5,  5,  6,  8, 10])

In [85]:
x = np.array([1,2,3])
y = np.array([4,5])

np.concatenate((x,y))

array([1, 2, 3, 4, 5])

In [90]:
z = np.array([
    [10,20,30],
    [40,50,60]
])

y = np.array([[1,2,3]])

In [92]:
np.concatenate((z,x), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [89]:
z

array([[10, 20, 30],
       [40, 50, 60]])

In [95]:
np.concatenate((z,y), axis = 0)

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  2,  3]])

In [96]:
x

array([1, 2, 3])

In [97]:
z

array([[10, 20, 30],
       [40, 50, 60]])

In [99]:
z.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [100]:
a 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
a = np.array([1,2,3,4,5])

In [102]:
a.shape

(5,)

In [103]:
a1 = a[np.newaxis,:]
a1.shape

(1, 5)

In [104]:
a

array([1, 2, 3, 4, 5])

In [108]:
np.array([(a<2) | (a>4)])

array([[ True, False, False, False,  True]])

In [110]:
a[(a<2) | (a>4)]

array([1, 5])

In [111]:
np.array([1,2])

array([1, 2])

In [112]:
np.array([2,1])

array([2, 1])

In [114]:
np.ones([2], dtype = int)

array([1, 1])

In [115]:
type(np.ones([2], dtype = int))

numpy.ndarray

In [116]:
np.ones([2], dtype = int).dtype

dtype('int32')

In [117]:
data = np.array([1,2])
ones = np.ones([2], dtype = int)

data + ones

array([2, 3])

In [118]:
ones

array([1, 1])

In [119]:
np.ones([1])

array([1.])

In [120]:
np.ones([4])

array([1., 1., 1., 1.])

In [121]:
data

array([1, 2])

In [122]:
ones

array([1, 1])

In [123]:
data.ndim

1

In [124]:
ones.ndim

1

In [125]:
x= np.array([1])

In [126]:
data + x

array([2, 3])

In [127]:
x

array([1])

In [128]:
data

array([1, 2])

In [129]:
y = np.array([1,2])

In [130]:
data + y

array([2, 4])

In [131]:
ones
data

array([1, 2])

In [132]:
data  - ones

array([0, 1])

In [133]:
data * ones

array([1, 2])

In [134]:
data/ones

array([1., 2.])

In [136]:
b = np.array([[1,2], [3,4]])

In [137]:
b.sum()

10

In [138]:
b.sum(axis = 0)

array([4, 6])

In [139]:
b.sum(axis = 1)

array([3, 7])

In [141]:
a = np.array([["a","b"], ["c","d"]])

In [142]:
a.sum()

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [144]:
a.sum(axis = 0 )

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [145]:
# Broadcasting is the mechanism by which Numpy is able to operate on arrays of varying shape. 
# The only condition being either dimensions of participating arrays must match or one of them should only 1 dimension.  

In [146]:
b

array([[1, 2],
       [3, 4]])

In [147]:
a

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [148]:
a*1

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('int32')) -> None

In [149]:
b * np.array([[[1,2]]])

array([[[1, 4],
        [3, 8]]])

In [150]:
np.array([[[1,2]]]).ndim

3

In [151]:
b.ndim

2

In [152]:
b

array([[1, 2],
       [3, 4]])

In [156]:
c = np.array([[[1,2,3]]])

In [157]:
b*c

ValueError: operands could not be broadcast together with shapes (2,2) (1,1,3) 

In [155]:
c

array([[[1, 2]]])

In [158]:
b

array([[1, 2],
       [3, 4]])

In [159]:
b.prod()

24

In [160]:
b.sum()

10

In [161]:
b.mean()

2.5

In [162]:
b.max()

4

In [163]:
b.min()

1

In [164]:
b

array([[1, 2],
       [3, 4]])

In [165]:
b.prod(axis = 0)

array([3, 8])

In [166]:
b.prod(axis = 1)

array([ 2, 12])

In [167]:
import random

In [170]:
np.random.random((3,2))

array([[0.85665502, 0.22772793],
       [0.97695275, 0.78890809],
       [0.33287473, 0.50852544]])

In [171]:
x = np.arange(10).reshape(2,5)

In [172]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [173]:
x.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [176]:
(x.transpose()).transpose()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [178]:
((x.transpose()).transpose()).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [179]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [181]:
x.flip

AttributeError: 'numpy.ndarray' object has no attribute 'flip'

In [182]:
np.flip(x)

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [183]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [184]:
np.flip(x, axis =1)

array([[4, 3, 2, 1, 0],
       [9, 8, 7, 6, 5]])

In [185]:
np.flip(x, axis = 0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [189]:
y = np.flip(x[1])

In [190]:
y

array([9, 8, 7, 6, 5])

In [191]:
x[1] = np.flip(x[1])

In [192]:
x

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])