In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
np.ones([2,2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [25]:
np.ones([3,2], dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [26]:
X = np.array([1,2,3,4])

In [27]:
np.ones_like(X)

array([1, 1, 1, 1])

In [29]:
np.ones([4,4], dtype = np.int8) *5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int8)

In [30]:
X

array([1, 2, 3, 4])

In [31]:
X = np.ones([3,3], dtype = np.int8)

In [32]:
X

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [34]:
np.ones_like(X) *7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]], dtype=int8)

In [36]:
np.identity(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [41]:
np.random.randint(10, size = 3)

array([8, 4, 3])

In [50]:
np.random.randn(3,3,3)

array([[[-2.72105307,  0.46065699, -1.08854554],
        [ 1.16853001, -2.28782141,  0.10416689],
        [-1.30094807,  0.02222091,  0.46326181]],

       [[-0.40048953, -0.17231875,  0.16683598],
        [-0.16171378,  0.37061898, -0.13920918],
        [ 1.26765176, -2.00800546, -0.65547759]],

       [[-1.30838932,  0.40498749,  0.59009984],
        [-1.03969616, -0.40514904, -0.31406824],
        [-0.54217568, -1.23294422, -0.93139928]]])

In [56]:
b = np.array(list1)

In [55]:
list1 = [1,2,3,5]

In [57]:
type(b)

numpy.ndarray

In [58]:
b

array([1, 2, 3, 5])

In [59]:
X = [x for x in range(5)]

In [60]:
np.array(X)

array([0, 1, 2, 3, 4])

In [61]:
Y = np.copy(X)

In [65]:
Y

array([0, 1, 2, 3, 4])

In [63]:
a = np.array(1)

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
a[a%2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [68]:
a = np.arange(0,11,2)

In [69]:
a

array([ 0,  2,  4,  6,  8, 10])

In [76]:
a = np.arange(10,0,-1)

In [77]:
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [78]:
a = np.arange(1,11)[::-1]

In [79]:
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [86]:
np.eye(3,3, dtype = np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [87]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
Z = np.arange(10)

In [95]:
np.dtype(Z).itemsize()

TypeError: Cannot construct a dtype from an array

In [96]:
Z.itemsize

4

In [97]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [98]:
A

NameError: name 'A' is not defined

In [100]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [101]:
A[1:-1]

array([[4, 5, 6],
       [7, 8, 9]])

In [102]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [103]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
B = np.array(A, np.float32)

In [110]:
B

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [119]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [122]:
A[0,0] = A[-1,-1]

In [123]:
A

array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [126]:
A[0,0],A[-1,-1] = A[-1,-1], A[0,0]

In [127]:
A

array([[12, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 10]])

In [128]:
X

[0, 1, 2, 3, 4]

In [129]:
X = np.arange(11,1,-1)

In [130]:
X

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [138]:
X.sort()

In [139]:
X

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [140]:
a = np.array([1,10,2,3,8,4])

In [141]:
a.sort()

In [142]:
a

array([ 1,  2,  3,  4,  8, 10])

In [143]:
A

array([[12, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 10]])

In [144]:
A[-1]

array([10, 11, 10])

In [145]:
A[-1] = 1

In [146]:
A

array([[12, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  1,  1]])

In [147]:
A

array([[12, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  1,  1]])

In [152]:
A[A>0]

array([12, 11, 12,  4,  5,  6,  7,  8,  9,  1,  1,  1])

In [153]:
A.all()

True

In [154]:
A.any()

True

In [155]:
B

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [162]:
C = np.array([
    [10,1,1],
    [1,1,0]
])

In [163]:
C.all()

False

In [164]:
C.any()

True

In [165]:
C

array([[10,  1,  1],
       [ 1,  1,  0]])

In [166]:
C.sum()

14

In [167]:
C.sum(axis = 0)

array([11,  2,  1])

In [168]:
C.sum(axis = 1)

array([12,  2])

In [ ]:
A