In [1]:
# Lets first discuss about the different types of arrays. 

import numpy as np 

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
b=np.array([0.5,1.5,3.6,9.2])

In [5]:
b

array([0.5, 1.5, 3.6, 9.2])

In [6]:
a.dtype

dtype('int32')

In [7]:
b.dtype

dtype('float64')

In [8]:
np.array([1,2,3,4], dtype = np.float64)

array([1., 2., 3., 4.])

In [9]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [10]:
c = np.array(["a","b","c"])

In [11]:
c.dtype

dtype('<U1')

In [12]:
import sys
d = np.array([{"a":1}, sys])

In [13]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [14]:
d.dtype

dtype('O')

In [15]:
a = np.array ( [
    [1,2,3],
    [4,5,6]
])

In [16]:
a.shape

(2, 3)

In [17]:
a.ndim

2

In [18]:
a.size

6

In [19]:
B = np.array([
    [
        [1,2],
        [5,6],
    ],
    [
        [12,23],
        [13,24]
    ]
])

In [20]:
B.shape

(2, 2, 2)

In [21]:
B.ndim

3

In [22]:
B.size

8

In [23]:
C = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
    ],
    [
        [12,32,45,56]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [24]:
C.dtype

NameError: name 'C' is not defined

In [ ]:
a

In [ ]:
a[1]

In [ ]:
a[1][2]

In [ ]:
a[1,2]

In [ ]:
a[:2]

In [ ]:
a[:]

In [ ]:
a[:]

In [ ]:
a[:1,:1]

In [25]:
a[:2,:1]

array([[1],
       [4]])

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a[1] = np.array([10,10,10])

In [28]:
a

array([[ 1,  2,  3],
       [10, 10, 10]])

In [29]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [30]:
a

array([0, 1, 2, 3, 4])

In [31]:
a

array([0, 1, 2, 3, 4])

In [32]:
a[0],a[1]

(0, 1)

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
a[[0,1]]

array([0, 1])

In [35]:
a

array([0, 1, 2, 3, 4])

In [36]:
a[[True, False, False, True,False]]

array([0, 3])

In [37]:
a>=2

array([False, False,  True,  True,  True])

In [38]:
a[a>=2]

array([2, 3, 4])

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a.mean()

2.0

In [41]:
a[a>a.mean()]

array([3, 4])

In [42]:
a[~(a>a.mean())]

array([0, 1, 2])

In [43]:
a[(a==0) | (a==1)]

array([0, 1])

In [44]:
a[(a==0)]

array([0])

In [45]:
a[(a>=2) & (a%2 == 0)]

array([2, 4])

In [46]:
import random

In [47]:
A = np.random.randint(100, size = (3,3))

In [48]:
A

array([[54, 23, 16],
       [69, 64, 75],
       [71, 81, 12]])

In [49]:
a 

array([0, 1, 2, 3, 4])

In [50]:
a = np.arange(5)

In [51]:
print(a <= 3)

[ True  True  True  True False]


In [52]:
import sys

In [53]:
sys.getsizeof(1)

28

In [54]:
sys.getsizeof("a")

42

In [55]:
sys.getsizeof("frgjh")

46

In [56]:
a=np.array(1, dtype = np.int8)

In [57]:
a

array(1, dtype=int8)

In [58]:
sys.getsizeof(a)

97

In [59]:
np.dtype(int).itemsize

4

In [60]:
np.dtype(np.int8).itemsize

1

In [61]:
np.dtype(float).itemsize

8

In [62]:
l = list(range(1000000))

In [63]:
a = np.arange(1000000)

In [64]:
%%time 
sum([x**2 for x in l])

CPU times: total: 46.9 ms
Wall time: 186 ms


333332833333500000

In [65]:
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 4.55 ms


584144992

In [66]:
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [67]:
a = np.array([1,2,3,4])

In [68]:
a

array([1, 2, 3, 4])

In [69]:
np.array([1,2,3,4]).nbytes

16

In [70]:
sys.getsizeof([1,2,3,4])

88

In [71]:
import sys
import numpy as np

In [72]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [73]:
a = np.array(["a","b","v"])

In [74]:
a

array(['a', 'b', 'v'], dtype='<U1')

In [75]:
b = np.array([12,24,56,345])

In [76]:
b

array([ 12,  24,  56, 345])

In [77]:
a[0]

'a'

In [78]:
a[2]

'v'

In [79]:
b[2]

56

In [80]:
c = (a[2],b[2])

In [81]:
a.dtype

dtype('<U1')

In [82]:
b.dtype

dtype('int32')

In [83]:
c

('v', 56)

In [84]:
type(c)

tuple

In [85]:
type(a)

numpy.ndarray

In [86]:
type(b)

numpy.ndarray

In [87]:
a[:]

array(['a', 'b', 'v'], dtype='<U1')

In [88]:
a[1:]

array(['b', 'v'], dtype='<U1')

In [89]:
b[1:]

array([ 24,  56, 345])

In [90]:
b[::2]

array([12, 56])

In [91]:
b

array([ 12,  24,  56, 345])

In [92]:
b[-1]

345

In [93]:
b[-2]

56

In [94]:
b[::-1]

array([345,  56,  24,  12])

In [95]:
b[0],b[2],b[1]

(12, 56, 24)

In [96]:
b[[0,2,1]]

array([12, 56, 24])

In [97]:
a

array(['a', 'b', 'v'], dtype='<U1')

In [98]:
d = np.array([1.5,2.6,4.6,5.6])

In [99]:
d

array([1.5, 2.6, 4.6, 5.6])

In [100]:
d.dtype

dtype('float64')

In [101]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [102]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
A.dtype

dtype('int32')

In [104]:
A.shape

(2, 3)

In [105]:
A.ndim

2

In [106]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [12,23,34],
        [45,56,67]
    ]
])

In [107]:
B.shape

(2, 2, 3)

In [108]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 23, 34],
        [45, 56, 67]]])

In [109]:
B.ndim

3

In [110]:
X= np.array(2)

In [111]:
X

array(2)

In [112]:
y = np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [113]:
Y = np.array([1,2,3])

In [114]:
X.dtype

dtype('int32')

In [115]:
X.ndim

0

In [116]:
Y.ndim

1

In [117]:
Y

array([1, 2, 3])

In [118]:
Z = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [119]:
Z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
Z.ndim

2

In [121]:
Z.shape

(3, 3)

In [122]:
z=np.array([[[[[1,2,3], [4,5,6], [7,8,9]]]]])

In [123]:
z.ndim

5

In [124]:
z.shape

(1, 1, 1, 3, 3)

In [125]:
B = np.array([
    [
        [12,3,4,5],
        [345,5,42,2]
    ],
    [
        [67,12,87,86],
        [234,768,98,546]
    ]
])

In [126]:
B.shape


(2, 2, 4)

In [127]:
B.ndim

3

In [128]:
B.size

16

In [129]:
C = np.array([
    [
        [12,3,4,5],
        [345,5,42,2]
    ],
    [
        [67,12,87,86]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [130]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [131]:
A[0][1]

2

In [132]:
A[0,1]

2

In [133]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [135]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
A[1]

array([4, 5, 6])

In [137]:
A[1]  = np.array([10,10,10])

In [138]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [139]:
A[2] = 99

In [140]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [141]:
a = np.array([1,2,3,4])

In [142]:
a.sum()

10

In [143]:
a.mean()

2.5

In [144]:
a.std()

1.118033988749895

In [145]:
a.var()

1.25

In [146]:
A 

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [147]:
A.sum()

333

In [148]:
A.mean()

37.0

In [149]:
A.std()

43.96463225012679

In [150]:
A.sum(axis = 0)

array([110, 111, 112])

In [151]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [152]:
A.sum(axis = 1)

array([  6,  30, 297])

In [153]:
A.sum(axis = 2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [154]:
B 

array([[[ 12,   3,   4,   5],
        [345,   5,  42,   2]],

       [[ 67,  12,  87,  86],
        [234, 768,  98, 546]]])

In [155]:
B.sum()

2316

In [156]:
B.sum(axis = 0)

array([[ 79,  15,  91,  91],
       [579, 773, 140, 548]])

In [157]:
B.sum(axis = 1)

array([[357,   8,  46,   7],
       [301, 780, 185, 632]])

In [158]:
B.sum(axis = 2)

array([[  24,  394],
       [ 252, 1646]])

In [159]:
B.sum(axis = -1)

array([[  24,  394],
       [ 252, 1646]])

In [160]:
B.sum(axis = -2)

array([[357,   8,  46,   7],
       [301, 780, 185, 632]])

In [161]:
B.sum(axis = -3)

array([[ 79,  15,  91,  91],
       [579, 773, 140, 548]])

In [162]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [163]:
A.mean(axis = 0)

array([36.66666667, 37.        , 37.33333333])

In [164]:
A.mean()

37.0

In [165]:
a = np.arange(4)

In [166]:
a

array([0, 1, 2, 3])

In [167]:
a + 10

array([10, 11, 12, 13])

In [168]:
a*10

array([ 0, 10, 20, 30])

In [169]:
a

array([0, 1, 2, 3])

In [170]:
a+=10

In [171]:
a

array([10, 11, 12, 13])

In [172]:
a

array([10, 11, 12, 13])

In [173]:
a = np.arange(5)

In [174]:
b = np.arange(5,10)

In [175]:
a

array([0, 1, 2, 3, 4])

In [176]:
b

array([5, 6, 7, 8, 9])

In [177]:
a+b

array([ 5,  7,  9, 11, 13])

In [178]:
a*b

array([ 0,  6, 14, 24, 36])

In [179]:
a[0],a[1]

(0, 1)

In [180]:
a[[0,1]]

array([0, 1])

In [181]:
a[[0,-1]]

array([0, 4])

In [182]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [183]:
A[0,1]

2

In [184]:
A[2,2]

99

In [185]:
A[0,2]

3

In [186]:
a

array([0, 1, 2, 3, 4])

In [187]:
a[[True,True,False,False,True]]

array([0, 1, 4])

In [188]:
a[[a[0,1,4]]]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [189]:
a[array([0,1,4])]

NameError: name 'array' is not defined

In [191]:
a

array([0, 1, 2, 3, 4])

In [192]:
a >= 2

array([False, False,  True,  True,  True])

In [193]:
a[a>=2]

array([2, 3, 4])

In [194]:
a(np.array[False, False,  True,  True,  True])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [195]:
a[[False, False,  True,  True,  True]]

array([2, 3, 4])

In [196]:
a

array([0, 1, 2, 3, 4])

In [197]:
a.mean()

2.0

In [198]:
a[a>a.mean()]

array([3, 4])

In [199]:
a[~(a>a.mean())]

array([0, 1, 2])

In [200]:
a[(a<=2) & (a%2 == 0)]

array([0, 2])

In [201]:
a[(a<2) | (a == 4)]

array([0, 1, 4])

In [202]:
import random

In [203]:
A = np.random.randint(100, size = (3,3))

In [204]:
A

array([[96, 67, 56],
       [28, 49, 66],
       [80, 89, 56]])

In [205]:
A>30

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [206]:
A[A>30]

array([96, 67, 56, 49, 66, 80, 89, 56])

In [207]:
A

array([[96, 67, 56],
       [28, 49, 66],
       [80, 89, 56]])

In [208]:
B

array([[[ 12,   3,   4,   5],
        [345,   5,  42,   2]],

       [[ 67,  12,  87,  86],
        [234, 768,  98, 546]]])

In [209]:
A = np.array([[1,2,3],
              [4,5,6]])

In [210]:
B = np.array([[10,20,30],[40,50,60]])

In [211]:
A.dot(B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
A = np.array([
    [1,2,3]
])

In [ ]:
B = np.array([4,5])

In [ ]:
A.dot(B)

In [ ]:
A = np.array([
    [1,2,3]
])

In [ ]:
B = np.array([
    [10],
    [30],
    [50]
])

In [ ]:
A.dot(B)

In [ ]:
A @ B

In [ ]:
B.T

In [ ]:
A

In [ ]:
B.T @ A

In [ ]:
sys.getsizeof(1)

In [ ]:
sys.getsizeof(10*100)

In [ ]:
np.dtype(int).itemsize

In [ ]:
np.dtype(np.int8).itemsize

In [ ]:
np.dtype(float).itemsize

In [ ]:
sys.getsizeof([1,2,3,4])

In [ ]:
np.array([1,2,3,4]).nbytes

In [ ]:
l = list(range(1000000))

In [ ]:
import numpy as np
a = np.arange(1000000)

In [ ]:
%time np.sum(a**2)

In [ ]:
%time sum([x**2 for x in l])

In [ ]:
np.random.random(size = 2)

In [ ]:
np.random.normal(size = 2)

In [ ]:
np.random.rand(2,4)

In [ ]:
np.arange(10)

In [ ]:
np.arange(5,10)

In [ ]:
np.arange(10,5)

In [ ]:
np.arange(0,1,0.1)

In [ ]:
np.arange(10).reshape(2,5)

In [ ]:
np.arange(10).reshape(5,2)

In [ ]:
np.linspace(0,1,5)

In [ ]:
np.linspace(0,1,20)

In [ ]:
np.linspace(0,1,20,False)

In [ ]:
np.linspace(0,1,20,True)

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((3,3,3))

In [ ]:
np.zeros((3,3), dtype = np.int8)

In [ ]:
np.ones(5)

In [ ]:
np.ones((2,2))

In [ ]:
np.empty(5)

In [ ]:
np.empty((3,3))

In [ ]:
np.empty(5)

In [ ]:
np.identity(3)

In [ ]:
np.identity(3,3)

In [ ]:
np.eye(3,3)

In [ ]:
np.eye(8,4)

In [ ]:
np.identity(8)

In [ ]:
np.eye(8,4, k =1 )

In [ ]:
np.eye(8,4, k=-3)

In [ ]:
"Hello World"[6]